### ISSUE TITLE
please do not include your Wordnik API key in a public repo

### ISSUE THREAD

**Issue by emckean** [vikneshwar/Wordnik-Command-Tool#1]
Hi! Thanks so much for creating this tool, but we'd like to ask that you NOT use our test API key in other tools. (edited as I first thought that you had used your own key).

Please put a placeholder here and encourage your users to apply for their own keys. 

Thanks!

**Comment by vikneshwar** [comment]
Oh sorry @emckean, actually I thought I should ask the user to configure their key, committed the code by mistake, will update the changes.

**Comment by vikneshwar** [comment]
Hi removed the key from the repo, will remove from npm too in a while .Thanks a lot for reporting it

**Comment by emckean** [comment]
Thank you so much for replying so quickly!

We hope to be able to obscure our key on our docs page soon, but it's
taking us a while to update it. :)

Thanks again for making such a nice tool!
